#!/usr/bin/env python
"""Self-contained reproduction script — generated by vivarium-dashboard.

Run from anywhere with the workspace's virtualenv, e.g.:
    .venv/bin/python draft-to-living-cell.py

Figures are written to:  reports/notebooks/figures
Set RERUN = False (below) to render the committed runs.db without re-simulating.
"""
import os as _os
import sys as _sys

# YAML / study text is UTF-8; force UTF-8 mode so file reads don't depend on the
# shell locale (a bare-CLI run under an ASCII locale otherwise crashes on non-ASCII).
if _os.environ.get("PYTHONUTF8") != "1":
    _os.environ["PYTHONUTF8"] = "1"
    _os.execv(_sys.executable, [_sys.executable, *_sys.argv])


# # From Draft to Living Cell
#
# _Investigation `draft-to-living-cell` — coder reproduction notebook._
#
# **Question.** How far can a cell be built compositionally — assembled from typed interfaces,
# each specified as a *draft* before any mechanism is chosen, then compiled into
# something that actually runs — and does that composition hold together into a
# whole cell that lives and dies?
#
# This investigation turns *A meta-modeler's guide to the cellular interface* into an executable test of compositional modeling. Each composition pattern in the paper is first represented as a draft: a typed biological interface and behavioral contract with no committed mechanism. It is then compiled by installing one or more concrete implementations — mechanistic, rule-based, data-driven, or otherwise — while preserving the declared interface.
#
# The point is not to assemble a single monolithic cell model. It is to test whether a biological model can remain open-ended as its mechanisms change, its assumptions fail, and its level of description shifts. Interfaces provide the places where models can be connected, isolated, replaced, or expanded; graph rewrites allow the composition itself to change through events such as growth, division, and disintegration.
#
# The investigation therefore follows the paper's central claim: composition is not the final architecture of a model, but an ongoing way of building one. Across the studies below, we ask whether the same biological specification can support alternative mechanisms, whether those mechanisms can be composed without losing their interface semantics, and whether the resulting system can reorganize as the biology demands. The endpoint is a composed whole cell that grows, divides, loses viability, and changes its own level of description — demonstrating the full arc from interface specification to living, changing simulation.
#
# ---
#
# This notebook re-runs each study with the workspace's own process-bigraph protocol and renders its figures. The text states the **question and parameters** only — the figures produced by each run are the results. Set `RERUN = False` in the setup cell to render the committed `runs.db` without re-simulating.

"""Self-contained reproduction of this investigation.

Generated by vivarium-dashboard (notebook_export). Each study below is re-run
live with the workspace's own process-bigraph protocol and its figures are
rendered from the resulting runs.db.
"""
import os
import sys
from pathlib import Path

# Resolve the repository root robustly so this notebook runs from a fresh clone
# at ANY path with no setup (no env var, no path editing). Priority:
#   1. $VIVARIUM_REPO, if it points at a real directory;
#   2. walk up from the notebook's working directory for the repo markers
#      (a directory holding both 'workspace/' and 'pyproject.toml') — Jupyter
#      starts in the notebook's dir, so a committed notebook finds its own root;
#   3. the absolute path it was generated for (back-compat for old layouts);
#   4. the current working directory (last resort).
def _find_repo_root(_start):
    for _cand in (_start, *_start.parents):
        if (_cand / "workspace").is_dir() and (_cand / "pyproject.toml").is_file():
            return _cand
    return None

REPO = None
_env = os.environ.get("VIVARIUM_REPO")
if _env and Path(_env).is_dir():
    REPO = Path(_env)
if REPO is None:
    REPO = _find_repo_root(Path.cwd().resolve())
if REPO is None and Path('/home/runner/work/viva-meta-modelers-guide/viva-meta-modelers-guide').is_dir():
    REPO = Path('/home/runner/work/viva-meta-modelers-guide/viva-meta-modelers-guide')
if REPO is None:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))
# Composite specs use repo-root-relative paths (datasets, caches), and the
# workspace's runner/renderer assume cwd == repo root — so run from there.
os.chdir(REPO)

# Re-simulate from scratch? Set False to render the committed runs.db (fast).
RERUN = True

# --- standard process-bigraph protocol: register the workspace's Core ---
from viva_meta_modelers_guide.core import build_core
core = build_core()

# --- imported from the repo this notebook was generated for ---


import contextlib as _contextlib, io as _io
@_contextlib.contextmanager
def quiet():
    """Silence the simulator's verbose per-step stdout so the notebook
    output stays readable (the figures below are the results)."""
    with _contextlib.redirect_stdout(_io.StringIO()):
        yield

import html as _htmlmod
def show_viz(_h, height=560):
    """Display a visualization's HTML in an isolated iframe.

    The figures embed their own scripts (e.g. Plotly); JupyterLab does not
    execute <script> tags from display(HTML(...)), so an iframe srcdoc is
    used instead — the browser runs the scripts inside the frame."""
    display(HTML(
        '<iframe srcdoc="{}" style="width:100%;height:{}px;border:0">'
        '</iframe>'.format(_htmlmod.escape(_h, quote=True), height)
    ))

import json as _json
def describe_spec(spec):
    """Print a composite spec's structure (parameters, processes, wiring)
    then the full editable dict. The spec is plain data — assign to any
    field (e.g. spec['state'][proc]['config'][...]) before building."""
    print("composite:", spec.get("name"))
    if spec.get("description"):
        print("description:", str(spec["description"]).strip())
    _params = spec.get("parameters") or {}
    if _params:
        print("\nparameters (filled into ${name} placeholders):")
        for _p, _pdef in _params.items():
            print(f"  {_p}: default={_pdef.get('default')!r}  type={_pdef.get('type')}")
    print("\nprocesses (node -> address):")
    for _node, _body in (spec.get("state") or {}).items():
        if not (isinstance(_body, dict) and _body.get("_type") == "process"):
            continue
        print(f"  {_node}  ->  {_body.get('address')}   interval={_body.get('interval')!r}")
        for _port in ("inputs", "outputs"):
            if _body.get(_port):
                print(f"      {_port} ports: {_body[_port]}")
    print("\nfull editable spec dict:")
    print(_json.dumps(spec, indent=2, default=str))

import base64 as _b64, pathlib as _pl
def _render_one(address, config, runs_db, study_yaml):
    """Generic figure renderer (no workspace render_study_viz.py):
    resolve an ``image:<relpath>`` visualization to displayable HTML,
    relative to the study directory."""
    addr = str(address or '')
    for _scheme in ('image:', 'file:', 'gif:', 'png:', 'svg:', 'jpg:', 'jpeg:'):
        if addr.startswith(_scheme):
            addr = addr[len(_scheme):]; break
    _p = _pl.Path(addr)
    if not _p.is_absolute():
        _p = _pl.Path(study_yaml).resolve().parent / _p
    if not _p.is_file():
        return f'<p style="color:#b91c1c">figure not found: {address}</p>'
    _suffix = _p.suffix.lower()
    if _suffix == '.svg':
        return _p.read_text(encoding='utf-8', errors='replace')
    if _suffix in ('.png', '.jpg', '.jpeg', '.gif', '.webp'):
        _mime = 'jpeg' if _suffix in ('.jpg', '.jpeg') else _suffix[1:]
        _data = _b64.b64encode(_p.read_bytes()).decode('ascii')
        return f'<img src="data:image/{_mime};base64,{_data}" style="max-width:100%"/>'
    if _suffix in ('.html', '.htm'):
        return _p.read_text(encoding='utf-8', errors='replace')
    return f'<p style="color:#6b7280">unsupported figure type: {address}</p>'

# ## Study: The Typed Interface (`typed-interface`)
#
# **Question.** Can the cellular boundary be specified as nothing but a set of typed, unit-bearing exchange ports (chemical, mechanical, electrical, thermal, plus growth rate, shape, objective, viability) with no committed mechanism, and then compiled — by installing one conforming handler — into a running, bounded, goal-directed cell whose interface is exactly the one declared?
#
# **Claim.** A cell can be specified at one level by its interface — typed exchange variables such as chemical flux, force, current, heat, growth, shape, objective, and viability — without committing to the mechanism that realizes those behaviors.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `interaction-modalities` | `viva_meta_modelers_guide.composites.fig04a-interaction-modalities` | 0 | — |
# | `cellular-interface` | `viva_meta_modelers_guide.composites.fig04b-cellular-interface` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig04a-interaction-modalities`** — `spec_viva_meta_modelers_guide_composites_fig04a_interaction_modalities` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig04a_interaction_modalities = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig04a-interaction-modalities.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig04a_interaction_modalities)

# === Edit parameters for composite 'Interaction Modalities' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'nutrient_exchange'  (local:NutrientExchange)
spec_viva_meta_modelers_guide_composites_fig04a_interaction_modalities['state']['nutrient_exchange']['config']['interval'] = 1.0

# process 'motile_force'  (local:MotileForce)
spec_viva_meta_modelers_guide_composites_fig04a_interaction_modalities['state']['motile_force']['config']['interval'] = 1.0

# process 'growth'  (local:Growth)
spec_viva_meta_modelers_guide_composites_fig04a_interaction_modalities['state']['growth']['config']['interval'] = 1.0

# process 'electrical_signaling'  (local:ElectricalSignaling)
spec_viva_meta_modelers_guide_composites_fig04a_interaction_modalities['state']['electrical_signaling']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig04b-cellular-interface`** — `spec_viva_meta_modelers_guide_composites_fig04b_cellular_interface` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig04b_cellular_interface = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig04b-cellular-interface.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig04b_cellular_interface)

# === Edit parameters for composite 'The Cellular Interface' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'cell'  (local:CellularInterface)
spec_viva_meta_modelers_guide_composites_fig04b_cellular_interface['state']['cell']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: typed-interface ===
STUDY = 'typed-interface'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **typed-interface-dynamics**

def _save_viz(study, slug, html):
    d = REPO / 'reports/notebooks/figures' / study
    d.mkdir(parents=True, exist_ok=True)
    out = d / (slug + '.html')
    out.write_text(html, encoding='utf-8')
    print('  wrote', out)


# typed-interface-dynamics
_save_viz('typed-interface', 'typed-interface-dynamics', _render_one('image:visualizations/typed-interface-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig04a-interaction-modalities**

# fig04a-interaction-modalities
_save_viz('typed-interface', 'fig04a-interaction-modalities', _render_one('image:visualizations/fig04a-interaction-modalities.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig04b-cellular-interface**

# fig04b-cellular-interface
_save_viz('typed-interface', 'fig04b-cellular-interface', _render_one('image:visualizations/fig04b-cellular-interface.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig04-illustration**

# fig04-illustration
_save_viz('typed-interface', 'fig04-illustration', _render_one('image:visualizations/fig04-illustration.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | volume-growth | kind=observable path=volume expr=max(volume) | op >= value 2.0 provenance executable run: max volume 6.11 from seed 0.5 (Monod uptake → yield·u growth) |
# | nutrient-depletion | kind=observable path=nutrient expr=last(nutrient) | op <= value 0.1 provenance Monod uptake depletes the finite pool (10.0) to ~0 by t=18 |
# | viability-cliff | kind=observable path=viability expr=last(viability) | op <= value 0.1 provenance Arrhenius: viability collapses once T > t_tol = 42 (crosses at t≈5.6, →0 by t=18) |
# | draft-is-inert | kind=observable path=volume expr=max(volume) | op >= value 2.0 provenance inert-draft run: max volume 0.50 (no mechanism → no growth); the control the correct model is contrasted against |

# ## Study: Closing the Loop (`closing-the-loop`)
#
# **Question.** Does the cell–environment coupling of Fig 5 close into a genuine sense/act loop when the environment is a real spatial field — i.e. does the cell read a diffusing chemical field, act back on it through an uptake flux, and grow from what it takes up, all over one shared field store?
#
# **Claim.** Sensing and acting are one coupling, not two: a cell and its environment can be specified as a shared interface over which the cell reads a field and acts back on it.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `cell-environment` | `viva_meta_modelers_guide.composites.fig05-cell-environment` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig05-cell-environment`** — `spec_viva_meta_modelers_guide_composites_fig05_cell_environment` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig05_cell_environment = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig05-cell-environment.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig05_cell_environment)

# === Edit parameters for composite 'Cell–Environment Coupling' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'reaction_diffusion'  (local:ReactionDiffusion)
spec_viva_meta_modelers_guide_composites_fig05_cell_environment['state']['reaction_diffusion']['config']['interval'] = 1.0

# process 'production_degradation'  (local:ProductionDegradation)
spec_viva_meta_modelers_guide_composites_fig05_cell_environment['state']['production_degradation']['config']['interval'] = 1.0

# process 'mechanical_stress'  (local:MechanicalStress)
spec_viva_meta_modelers_guide_composites_fig05_cell_environment['state']['mechanical_stress']['config']['interval'] = 1.0

# process 'single_cell_processes'  (local:SingleCellProcesses)
spec_viva_meta_modelers_guide_composites_fig05_cell_environment['state']['single_cell_processes']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: closing-the-loop ===
STUDY = 'closing-the-loop'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **closing-the-loop-dynamics**

# closing-the-loop-dynamics
_save_viz('closing-the-loop', 'closing-the-loop-dynamics', _render_one('image:visualizations/closing-the-loop-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig05-cell-environment**

# fig05-cell-environment
_save_viz('closing-the-loop', 'fig05-cell-environment', _render_one('image:visualizations/fig05-cell-environment.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig05-illustration**

# fig05-illustration
_save_viz('closing-the-loop', 'fig05-illustration', _render_one('image:visualizations/fig05-illustration.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | biomass-growth | kind=observable path=biomass expr=last(biomass) | op >= value 0.3 provenance cell sink grows from the diffusing field (exec last≈0.66) |
# | nutrient-uptake | kind=observable path=uptake_total expr=last(uptake_total) | op >= value 0.5 provenance Monod uptake at the site draws down the bolus (exec last≈0.95) |
# | draft-is-inert | kind=observable path=biomass expr=last(biomass) | op >= value 0.3 provenance inert-draft run stays at seed (no mechanism → no dynamics) |

# ## Study: One Interface, Three Mechanisms (`one-interface-three-mechanisms`)
#
# **Question.** Can a single metabolism interface — the ports nutrients ⇒ {biomass, energy, entropy, secretions} of Fig 6 — be realized by three genuinely different mechanisms (a lumped-yield process, a saturating-kinetic process, and a real flux-balance optimization via COBRApy) while every other part of the composite, and the interface itself, stays byte-for-byte the same?
#
# **Claim.** One metabolic interface can be realized by many mechanisms — a lumped yield, saturating kinetics, or a real flux-balance solver — without changing what the interface exposes.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `disintegration` | `viva_meta_modelers_guide.composites.fig06-disintegration` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig06-disintegration`** — `spec_viva_meta_modelers_guide_composites_fig06_disintegration` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig06_disintegration = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig06-disintegration.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig06_disintegration)

# === Edit parameters for composite 'Cell Disintegration' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'coarse_grained_metabolism'  (local:CoarseGrainedMetabolism)
spec_viva_meta_modelers_guide_composites_fig06_disintegration['state']['coarse_grained_metabolism']['config']['interval'] = 1.0

# process 'catalyzed_reaction_network'  (local:CatalyzedReactionNetwork)
spec_viva_meta_modelers_guide_composites_fig06_disintegration['state']['catalyzed_reaction_network']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: one-interface-three-mechanisms ===
STUDY = 'one-interface-three-mechanisms'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **one-interface-three-mechanisms-dynamics**

# one-interface-three-mechanisms-dynamics
_save_viz('one-interface-three-mechanisms', 'one-interface-three-mechanisms-dynamics', _render_one('image:visualizations/one-interface-three-mechanisms-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig06-disintegration**

# fig06-disintegration
_save_viz('one-interface-three-mechanisms', 'fig06-disintegration', _render_one('image:visualizations/fig06-disintegration.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig06-illustration**

# fig06-illustration
_save_viz('one-interface-three-mechanisms', 'fig06-illustration', _render_one('image:visualizations/fig06-illustration.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | biomass-reaches-6 | kind=observable path=biomass expr=last(biomass) | op >= value 6.0 provenance OVER-REACH: exceeds the yield·S0=5.0 mass-conservation cap |

# ## Study: Molecular Channels (`molecular-channels`)
#
# **Question.** When a description drops to the molecular grain (Fig 7), can a single molecular mechanism act as a transducer across four typed physical channels at once — chemical, electrical, mechanical, thermal — each carried on its own port in its own unit, without the channels collapsing into one lumped output?
#
# **Claim.** At the molecular level a single mechanism can transduce several physical channels at once — chemical, electrical, mechanical, thermal — each carried on its own typed port.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `molecular-mechanism` | `viva_meta_modelers_guide.composites.fig07-molecular-mechanism` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig07-molecular-mechanism`** — `spec_viva_meta_modelers_guide_composites_fig07_molecular_mechanism` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig07_molecular_mechanism = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig07-molecular-mechanism.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig07_molecular_mechanism)

# === Edit parameters for composite 'A Molecular Mechanism' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'molecular_mechanism'  (local:MolecularMechanism)
spec_viva_meta_modelers_guide_composites_fig07_molecular_mechanism['state']['molecular_mechanism']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: molecular-channels ===
STUDY = 'molecular-channels'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **molecular-channels-dynamics**

# molecular-channels-dynamics
_save_viz('molecular-channels', 'molecular-channels-dynamics', _render_one('image:visualizations/molecular-channels-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig07-molecular-mechanism**

# fig07-molecular-mechanism
_save_viz('molecular-channels', 'fig07-molecular-mechanism', _render_one('image:visualizations/fig07-molecular-mechanism.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig07-illustration**

# fig07-illustration
_save_viz('molecular-channels', 'fig07-illustration', _render_one('image:visualizations/fig07-illustration.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | product-formation | kind=observable path=product expr=last(product) | op >= value 2.0 provenance chemical turnover yields product (exec last≈4.8) |
# | substrate-consumed | kind=observable path=substrate expr=last(substrate) | op <= value 0.5 provenance substrate pool consumed to ~0 (exec last≈0.0 from 8.0) |
# | heat-generated | kind=observable path=heat expr=last(heat) | op >= value 1.0 provenance turnover dissipates heat (exec last≈3.2) |
# | draft-is-inert | kind=observable path=product expr=last(product) | op >= value 2.0 provenance inert-draft run stays at seed (no mechanism → no dynamics) |

# ## Study: The Nested Cell (`the-nested-cell`)
#
# **Question.** How do molecules compose into a cell? Can the Fig 8 molecular composition be authored as a deeply nested place graph — membrane, cytoplasm, nucleus, chromosome, chromatin, nucleosome — with a gene-expression cascade wired to its deepest leaves, and does compilation preserve the interface even six levels down?
#
# **Claim.** Molecular composition is a nested containment hierarchy, and an interface can be preserved even when it is wired to the deepest levels of that nesting.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `nested-hierarchy` | `viva_meta_modelers_guide.composites.fig08-nested-hierarchy` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig08-nested-hierarchy`** — `spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig08-nested-hierarchy.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy)

# === Edit parameters for composite 'Nested Molecular Hierarchy' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'transmembrane_transport'  (local:TransmembraneTransport)
spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy['state']['transmembrane_transport']['config']['interval'] = 1.0

# process 'replication_and_repair'  (local:ReplicationAndRepair)
spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy['state']['replication_and_repair']['config']['interval'] = 1.0

# process 'cell_metabolism'  (local:CellMetabolism)
spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy['state']['cell_metabolism']['config']['interval'] = 1.0

# process 'transcription'  (local:Transcription)
spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy['state']['transcription']['config']['interval'] = 1.0

# process 'translation'  (local:Translation)
spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy['state']['translation']['config']['interval'] = 1.0

# process 'subunit_assembly'  (local:SubunitAssembly)
spec_viva_meta_modelers_guide_composites_fig08_nested_hierarchy['state']['subunit_assembly']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: the-nested-cell ===
STUDY = 'the-nested-cell'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **the-nested-cell-dynamics**

# the-nested-cell-dynamics
_save_viz('the-nested-cell', 'the-nested-cell-dynamics', _render_one('image:visualizations/the-nested-cell-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig08-nested-hierarchy**

# fig08-nested-hierarchy
_save_viz('the-nested-cell', 'fig08-nested-hierarchy', _render_one('image:visualizations/fig08-nested-hierarchy.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig08-illustration**

# fig08-illustration
_save_viz('the-nested-cell', 'fig08-illustration', _render_one('image:visualizations/fig08-illustration.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | protein-expressed | kind=observable path=protein expr=last(protein) | op >= value 3.0 provenance central dogma expresses protein (exec last≈10.5) |
# | mrna-transcribed | kind=observable path=mrna expr=last(mrna) | op >= value 0.5 provenance gene transcribed to mRNA (exec last≈2.4) |
# | draft-is-inert | kind=observable path=protein expr=last(protein) | op >= value 3.0 provenance inert-draft run stays at seed (no mechanism → no dynamics) |

# ## Study: Self-Made (`self-made`)
#
# **Question.** How does a cell hold itself together? Does the Fig 9 composition express autopoiesis — metabolism, containment, and replication mutually producing one another — and does that same closure appear when each function is realized at a coarse, a self-organized, or a molecular grain?
#
# **Claim.** A cell holds itself together through closure: metabolism, containment, and replication each produce what the others need, so the organization sustains itself.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `coarse-graining` | `viva_meta_modelers_guide.composites.fig09a-coarse-graining` | 0 | — |
# | `minimal-cell` | `viva_meta_modelers_guide.composites.fig09b-minimal-cell` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig09a-coarse-graining`** — `spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig09a-coarse-graining.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining)

# === Edit parameters for composite 'Self-Organization & Coarse-Graining' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'metabolism_closure'  (local:MetabolismClosure)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['metabolism_closure']['config']['interval'] = 1.0

# process 'autocatalysis'  (local:Autocatalysis)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['autocatalysis']['config']['interval'] = 1.0

# process 'containment_closure'  (local:ContainmentClosure)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['containment_closure']['config']['interval'] = 1.0

# process 'membrane_self_assembly'  (local:MembraneSelfAssembly)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['membrane_self_assembly']['config']['interval'] = 1.0

# process 'lipid_aggregation'  (local:LipidAggregation)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['lipid_aggregation']['config']['interval'] = 1.0

# process 'replication_closure'  (local:ReplicationClosure)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['replication_closure']['config']['interval'] = 1.0

# process 'template_replication'  (local:TemplateReplication)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['template_replication']['config']['interval'] = 1.0

# process 'template_directed_synthesis'  (local:TemplateDirectedSynthesis)
spec_viva_meta_modelers_guide_composites_fig09a_coarse_graining['state']['template_directed_synthesis']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig09b-minimal-cell`** — `spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig09b-minimal-cell.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell)

# === Edit parameters for composite 'The Minimal Cell' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'minimal_cell_containment'  (local:MinimalCellContainment)
spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell['state']['minimal_cell_containment']['config']['interval'] = 1.0

# process 'minimal_cell_metabolism'  (local:MinimalCellMetabolism)
spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell['state']['minimal_cell_metabolism']['config']['interval'] = 1.0

# process 'gene_expression'  (local:GeneExpression)
spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell['state']['gene_expression']['config']['interval'] = 1.0

# process 'minimal_cell_replication'  (local:MinimalCellReplication)
spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell['state']['minimal_cell_replication']['config']['interval'] = 1.0

# process 'diffusion'  (local:Diffusion)
spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell['state']['diffusion']['config']['interval'] = 1.0

# process 'reactions'  (local:Reactions)
spec_viva_meta_modelers_guide_composites_fig09b_minimal_cell['state']['reactions']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: self-made ===
STUDY = 'self-made'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **self-made-dynamics**

# self-made-dynamics
_save_viz('self-made', 'self-made-dynamics', _render_one('image:visualizations/self-made-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig09a-coarse-graining**

# fig09a-coarse-graining
_save_viz('self-made', 'fig09a-coarse-graining', _render_one('image:visualizations/fig09a-coarse-graining.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig09b-minimal-cell**

# fig09b-minimal-cell
_save_viz('self-made', 'fig09b-minimal-cell', _render_one('image:visualizations/fig09b-minimal-cell.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig09-illustration**

# fig09-illustration
_save_viz('self-made', 'fig09-illustration', _render_one('image:visualizations/fig09-illustration.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig09-illustration-2**

# fig09-illustration-2
_save_viz('self-made', 'fig09-illustration-2', _render_one('image:visualizations/fig09-illustration-2.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | membrane-sustains | kind=observable path=membrane expr=last(membrane) | op >= value 1.0 provenance intact closure self-sustains the membrane (exec last≈2.1) |
# | enzyme-maintained | kind=observable path=enzyme expr=last(enzyme) | op >= value 0.5 provenance the enzyme pool is held up by the closure (exec last≈1.1) |
# | knockout-collapses | kind=observable path=membrane expr=last(membrane) | op >= value 1.0 provenance draft/knockout run collapses (no mechanism / no closure) |

# ## Study: Divide (`divide`)
#
# **Question.** Is cell division in Fig 10 a genuine structural rewrite of the place graph — a single cell node actually becoming two daughter nodes at runtime — rather than a pre-declared post-structure that is merely animated?
#
# **Claim.** Division is a change to the composition itself: one cell becomes two through a graph rewrite that creates new nodes at runtime, not a pre-drawn pair.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `division-rewrite` | `viva_meta_modelers_guide.composites.fig10-1-rewrite` | 0 | — |
# | `division` | `viva_meta_modelers_guide.composites.fig10-1-division` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig10-1-rewrite`** — `spec_viva_meta_modelers_guide_composites_fig10_1_rewrite` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_1_rewrite = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-1-rewrite.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_1_rewrite)

# === Edit parameters for composite 'Cell Division — Live Topology' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'cell_cycle'  (local:CellCycleDivision)
spec_viva_meta_modelers_guide_composites_fig10_1_rewrite['state']['cell_cycle']['interval'] = 1.0
spec_viva_meta_modelers_guide_composites_fig10_1_rewrite['state']['cell_cycle']['config']['cycle'] = 3.0

# **Composite `viva_meta_modelers_guide.composites.fig10-1-division`** — `spec_viva_meta_modelers_guide_composites_fig10_1_division` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_1_division = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-1-division.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_1_division)

# === Edit parameters for composite 'Cell Division — Draft Interface' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'dna_replication'  (local:DNAReplication)
spec_viva_meta_modelers_guide_composites_fig10_1_division['state']['dna_replication']['config']['interval'] = 1.0

# process 'segregate_chromosome'  (local:SegregateChromosome)
spec_viva_meta_modelers_guide_composites_fig10_1_division['state']['segregate_chromosome']['config']['interval'] = 1.0

# process 'divide'  (local:Divide)
spec_viva_meta_modelers_guide_composites_fig10_1_division['state']['divide']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: divide ===
STUDY = 'divide'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **divide-dynamics**

# divide-dynamics
_save_viz('divide', 'divide-dynamics', _render_one('image:visualizations/divide-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig10-1-division**

# fig10-1-division
_save_viz('divide', 'fig10-1-division', _render_one('image:visualizations/fig10-1-division.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig10-illustration**

# fig10-illustration
_save_viz('divide', 'fig10-illustration', _render_one('image:visualizations/fig10-illustration.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | division-occurs | kind=observable path=cell_count expr=last(cell_count) | op >= value 2.0 provenance lineage divides (exec cell_count 1→14) |
# | nutrient-consumed | kind=observable path=nutrient expr=last(nutrient) | op <= value 5.0 provenance growing lineage draws nutrient down (exec last≈1.1 from 20) |
# | draft-is-inert | kind=observable path=cell_count expr=last(cell_count) | op >= value 2.0 provenance inert-draft run stays at seed (no mechanism → no dynamics) |

# ## Study: Biofilm (`biofilm`)
#
# **Question.** Can multicellular development (Fig 10) be expressed as compositional reorganization — individual cells attaching, secreting extracellular matrix, and assembling into a biofilm that is itself a higher-level composite with its own aggregate observables?
#
# **Claim.** Development is composition at a higher level: individual cells reorganize into a community that is itself a composite with its own aggregate behavior.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `development-rewrite` | `viva_meta_modelers_guide.composites.fig10-2-rewrite` | 0 | — |
# | `development` | `viva_meta_modelers_guide.composites.fig10-2-development` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig10-2-rewrite`** — `spec_viva_meta_modelers_guide_composites_fig10_2_rewrite` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_2_rewrite = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-2-rewrite.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_2_rewrite)

# === Edit parameters for composite 'Biofilm Development — Live Topology' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'development'  (local:BiofilmDevelopment)
spec_viva_meta_modelers_guide_composites_fig10_2_rewrite['state']['development']['interval'] = 1.0
spec_viva_meta_modelers_guide_composites_fig10_2_rewrite['state']['development']['config']['grow_every'] = 2.0
spec_viva_meta_modelers_guide_composites_fig10_2_rewrite['state']['development']['config']['capacity'] = 5.0

# **Composite `viva_meta_modelers_guide.composites.fig10-2-development`** — `spec_viva_meta_modelers_guide_composites_fig10_2_development` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_2_development = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-2-development.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_2_development)

# === Edit parameters for composite 'Biofilm Development — Draft Interface' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'surface_attachment'  (local:SurfaceAttachment)
spec_viva_meta_modelers_guide_composites_fig10_2_development['state']['surface_attachment']['config']['interval'] = 1.0

# process 'ecm_secretion'  (local:ECMSecretion)
spec_viva_meta_modelers_guide_composites_fig10_2_development['state']['ecm_secretion']['config']['interval'] = 1.0

# process 'biofilm_growth'  (local:BiofilmGrowth)
spec_viva_meta_modelers_guide_composites_fig10_2_development['state']['biofilm_growth']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: biofilm ===
STUDY = 'biofilm'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **biofilm-dynamics**

# biofilm-dynamics
_save_viz('biofilm', 'biofilm-dynamics', _render_one('image:visualizations/biofilm-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig10-2-development**

# fig10-2-development
_save_viz('biofilm', 'fig10-2-development', _render_one('image:visualizations/fig10-2-development.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig10-illustration-2**

# fig10-illustration-2
_save_viz('biofilm', 'fig10-illustration-2', _render_one('image:visualizations/fig10-illustration-2.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | colony-growth | kind=observable path=cells expr=last(cells) | op >= value 2.0 provenance logistic colony grows toward K (exec last≈5.0) |
# | ecm-production | kind=observable path=ecm expr=last(ecm) | op >= value 5.0 provenance colony secretes extracellular matrix (exec last≈21.8) |
# | draft-is-inert | kind=observable path=cells expr=last(cells) | op >= value 2.0 provenance inert-draft run stays at seed (no mechanism → no dynamics) |

# ## Study: Evolve (`evolve`)
#
# **Question.** Can evolution (Fig 10) be modelled compositionally — variation and selection acting on a population, and, crucially, the *addition of a new interface port* to a lineage — so that the interface set itself changes over evolutionary time?
#
# **Claim.** Evolution is a composition that rewrites itself over time — variants compete, selection acts, and a lineage can acquire an entirely new interface port.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `evolution-rewrite` | `viva_meta_modelers_guide.composites.fig10-3-rewrite` | 0 | — |
# | `evolution` | `viva_meta_modelers_guide.composites.fig10-3-evolution` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig10-3-rewrite`** — `spec_viva_meta_modelers_guide_composites_fig10_3_rewrite` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_3_rewrite = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-3-rewrite.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_3_rewrite)

# === Edit parameters for composite 'Evolution — Live Topology' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'evolution'  (local:LineageEvolution)
spec_viva_meta_modelers_guide_composites_fig10_3_rewrite['state']['evolution']['interval'] = 1.0
spec_viva_meta_modelers_guide_composites_fig10_3_rewrite['state']['evolution']['config']['generation'] = 2.0
spec_viva_meta_modelers_guide_composites_fig10_3_rewrite['state']['evolution']['config']['mutate_at'] = 4.0
spec_viva_meta_modelers_guide_composites_fig10_3_rewrite['state']['evolution']['config']['founders'] = 3.0
spec_viva_meta_modelers_guide_composites_fig10_3_rewrite['state']['evolution']['config']['capacity'] = 6.0

# **Composite `viva_meta_modelers_guide.composites.fig10-3-evolution`** — `spec_viva_meta_modelers_guide_composites_fig10_3_evolution` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_3_evolution = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-3-evolution.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_3_evolution)

# === Edit parameters for composite 'Evolution — Draft Interface' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'variation'  (local:Variation)
spec_viva_meta_modelers_guide_composites_fig10_3_evolution['state']['variation']['config']['interval'] = 1.0

# process 'selection'  (local:Selection)
spec_viva_meta_modelers_guide_composites_fig10_3_evolution['state']['selection']['config']['interval'] = 1.0

# process 'port_addition'  (local:PortAddition)
spec_viva_meta_modelers_guide_composites_fig10_3_evolution['state']['port_addition']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: evolve ===
STUDY = 'evolve'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **evolve-dynamics**

# evolve-dynamics
_save_viz('evolve', 'evolve-dynamics', _render_one('image:visualizations/evolve-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# **fig10-3-evolution**

# fig10-3-evolution
_save_viz('evolve', 'fig10-3-evolution', _render_one('image:visualizations/fig10-3-evolution.svg', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# **fig10-illustration-3**

# fig10-illustration-3
_save_viz('evolve', 'fig10-illustration-3', _render_one('image:visualizations/fig10-illustration-3.png', {'chart': 'image'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | capability-emerges | kind=observable path=capability expr=last(capability) | op >= value 2.0 provenance a new interface capability rides the sweep (exec last≈7.6) |
# | mutant-outgrows | kind=observable path=n_mut expr=last(n_mut) | op >= value 0.2 provenance the fitter variant sweeps (mut fraction 0.05→0.70) |
# | draft-is-inert | kind=observable path=capability expr=last(capability) | op >= value 2.0 provenance draft/knockout run collapses (no mechanism / no closure) |

# ## Study: The Living Atlas (`the-living-atlas`)
#
# **Question.** Do all of the paper's semantic figures actually compile to executables that run, and — the real test of composition — can the independently-authored figure mechanisms be assembled into a single whole cell that lives the paper's full arc: grow, divide, and die?
#
# **Claim.** The patterns compose: independently-specified interfaces and mechanisms can be assembled into one cell that lives the paper's full arc.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `fig06-exec-coarse` | `viva_meta_modelers_guide.composites.fig06-executable-coarse` | 0 | — |
# | `fig06-exec-kinetic` | `viva_meta_modelers_guide.composites.fig06-executable-kinetic` | 0 | — |
# | `fig04b-exec` | `viva_meta_modelers_guide.composites.fig04b-executable` | 0 | — |
# | `fig05-exec-spatial` | `viva_meta_modelers_guide.composites.fig05-executable` | 0 | — |
# | `fig06-exec-fba` | `viva_meta_modelers_guide.composites.fig06-executable-fba` | 0 | — |
# | `fig07-exec-molecular` | `viva_meta_modelers_guide.composites.fig07-executable` | 0 | — |
# | `fig08-exec-hierarchy` | `viva_meta_modelers_guide.composites.fig08-executable` | 0 | — |
# | `fig09a-exec-coarse-graining` | `viva_meta_modelers_guide.composites.fig09a-executable` | 0 | — |
# | `fig09b-exec-minimal-cell` | `viva_meta_modelers_guide.composites.fig09b-executable` | 0 | — |
# | `fig10-1-exec-division` | `viva_meta_modelers_guide.composites.fig10-1-executable` | 0 | — |
# | `fig10-2-exec-development` | `viva_meta_modelers_guide.composites.fig10-2-executable` | 0 | — |
# | `fig10-3-exec-evolution` | `viva_meta_modelers_guide.composites.fig10-3-executable` | 0 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_meta_modelers_guide.composites.fig06-executable-coarse`** — `spec_viva_meta_modelers_guide_composites_fig06_executable_coarse` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig06-executable-coarse.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig06_executable_coarse)

# === Edit parameters for composite 'Cell Disintegration — Coarse-Grained' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'coarse_grained_metabolism'  (local:CoarseMetabolism)
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse['state']['coarse_grained_metabolism']['config']['biomass_yield'] = 0.5
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse['state']['coarse_grained_metabolism']['config']['energy_yield'] = 0.3
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse['state']['coarse_grained_metabolism']['config']['entropy_rate'] = 0.1
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse['state']['coarse_grained_metabolism']['config']['secretion_frac'] = 0.2
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse['state']['coarse_grained_metabolism']['config']['interval'] = 1.0

# process 'catalyzed_reaction_network'  (local:KineticReactionNetwork)
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse['state']['catalyzed_reaction_network']['config']['k'] = 0.2
spec_viva_meta_modelers_guide_composites_fig06_executable_coarse['state']['catalyzed_reaction_network']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig06-executable-kinetic`** — `spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig06-executable-kinetic.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic)

# === Edit parameters for composite 'Cell Disintegration — Kinetic Metabolism' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'coarse_grained_metabolism'  (local:KineticMetabolism)
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['coarse_grained_metabolism']['config']['vmax'] = 1.0
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['coarse_grained_metabolism']['config']['km'] = 0.5
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['coarse_grained_metabolism']['config']['biomass_yield'] = 0.5
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['coarse_grained_metabolism']['config']['energy_yield'] = 0.3
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['coarse_grained_metabolism']['config']['entropy_rate'] = 0.1
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['coarse_grained_metabolism']['config']['secretion_frac'] = 0.2
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['coarse_grained_metabolism']['config']['interval'] = 1.0

# process 'catalyzed_reaction_network'  (local:KineticReactionNetwork)
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['catalyzed_reaction_network']['config']['k'] = 0.2
spec_viva_meta_modelers_guide_composites_fig06_executable_kinetic['state']['catalyzed_reaction_network']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig04b-executable`** — `spec_viva_meta_modelers_guide_composites_fig04b_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig04b_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig04b-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig04b_executable)

# === Edit parameters for composite 'The Cellular Interface — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'cell'  (local:CellularInterfaceHandler)
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['uptake_rate'] = 0.8
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['growth_max'] = 0.6
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['km'] = 0.5
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['shape_growth_coupling'] = 1.0
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['objective_yield'] = 0.5
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['temp_opt'] = 37.0
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['temp_tol'] = 5.0
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['viability_relax'] = 0.3
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['viability_init'] = 1.0
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['elasticity'] = 0.1
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['membrane_conductance'] = 0.05
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['thermal_conductance'] = 0.02
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['signaling_gain'] = 0.4
spec_viva_meta_modelers_guide_composites_fig04b_executable['state']['cell']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig05-executable`** — `spec_viva_meta_modelers_guide_composites_fig05_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig05_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig05-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig05_executable)

# === Edit parameters for composite 'Cell–Environment Coupling — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'reaction_diffusion'  (local:SpatialDiffusion)
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['reaction_diffusion']['config']['diffusivity'] = 0.2
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['reaction_diffusion']['config']['interval'] = 1.0

# process 'production_degradation'  (local:ProductionDegradationField)
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['production_degradation']['config']['source_index'] = 0
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['production_degradation']['config']['source_rate'] = 0.05
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['production_degradation']['config']['decay_rate'] = 0.01
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['production_degradation']['config']['interval'] = 1.0

# process 'mechanical_stress'  (local:MechanicalRelax)
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['mechanical_stress']['config']['relax_rate'] = 0.3
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['mechanical_stress']['config']['interval'] = 1.0

# process 'single_cell_processes'  (local:SingleCellSpatial)
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['single_cell_processes']['config']['cell_index'] = 4
spec_viva_meta_modelers_guide_composites_fig05_executable['state']['single_cell_processes']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig06-executable-fba`** — `spec_viva_meta_modelers_guide_composites_fig06_executable_fba` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig06_executable_fba = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig06-executable-fba.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig06_executable_fba)

# === Edit parameters for composite 'Cell Disintegration — FBA Metabolism' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'coarse_grained_metabolism'  (local:FBAMetabolism)
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['coarse_grained_metabolism']['config']['uptake_scale'] = 1.0
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['coarse_grained_metabolism']['config']['biomass_capacity'] = 0.8
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['coarse_grained_metabolism']['config']['biomass_yield'] = 0.5
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['coarse_grained_metabolism']['config']['energy_yield'] = 0.3
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['coarse_grained_metabolism']['config']['entropy_rate'] = 0.1
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['coarse_grained_metabolism']['config']['secretion_frac'] = 0.2
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['coarse_grained_metabolism']['config']['interval'] = 1.0

# process 'catalyzed_reaction_network'  (local:KineticReactionNetwork)
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['catalyzed_reaction_network']['config']['k'] = 0.2
spec_viva_meta_modelers_guide_composites_fig06_executable_fba['state']['catalyzed_reaction_network']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig07-executable`** — `spec_viva_meta_modelers_guide_composites_fig07_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig07_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig07-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig07_executable)

# === Edit parameters for composite 'A Molecular Mechanism — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'molecular_mechanism'  (local:MolecularMechanismHandler)
spec_viva_meta_modelers_guide_composites_fig07_executable['state']['molecular_mechanism']['config']['catalysis'] = 0.6
spec_viva_meta_modelers_guide_composites_fig07_executable['state']['molecular_mechanism']['config']['dissipation'] = 0.2
spec_viva_meta_modelers_guide_composites_fig07_executable['state']['molecular_mechanism']['config']['conductance'] = 0.3
spec_viva_meta_modelers_guide_composites_fig07_executable['state']['molecular_mechanism']['config']['coupling'] = 0.4
spec_viva_meta_modelers_guide_composites_fig07_executable['state']['molecular_mechanism']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig08-executable`** — `spec_viva_meta_modelers_guide_composites_fig08_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig08_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig08-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig08_executable)

# === Edit parameters for composite 'Nested Molecular Hierarchy — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'transmembrane_transport'  (local:TransmembraneTransportODE)
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['transmembrane_transport']['config']['k'] = 0.3
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['transmembrane_transport']['config']['metabolite_frac'] = 0.1
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['transmembrane_transport']['config']['interval'] = 1.0

# process 'replication_and_repair'  (local:ReplicationAndRepairODE)
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['replication_and_repair']['config']['k'] = 0.05
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['replication_and_repair']['config']['interval'] = 1.0

# process 'cell_metabolism'  (local:CellMetabolismODE)
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['cell_metabolism']['config']['k'] = 0.25
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['cell_metabolism']['config']['metabolite_yield'] = 0.6
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['cell_metabolism']['config']['energy_yield'] = 0.4
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['cell_metabolism']['config']['interval'] = 1.0

# process 'transcription'  (local:TranscriptionODE)
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['transcription']['config']['k'] = 0.3
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['transcription']['config']['interval'] = 1.0

# process 'translation'  (local:TranslationODE)
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['translation']['config']['k'] = 0.4
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['translation']['config']['km'] = 0.5
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['translation']['config']['interval'] = 1.0

# process 'subunit_assembly'  (local:SubunitAssemblyODE)
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['subunit_assembly']['config']['k'] = 0.2
spec_viva_meta_modelers_guide_composites_fig08_executable['state']['subunit_assembly']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig09a-executable`** — `spec_viva_meta_modelers_guide_composites_fig09a_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig09a_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig09a-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig09a_executable)

# === Edit parameters for composite 'Self-Organization & Coarse-Graining — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'metabolism_closure'  (local:MetabolismClosureODE)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['metabolism_closure']['config']['metabolite_yield'] = 0.6
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['metabolism_closure']['config']['entropy_rate'] = 0.1
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['metabolism_closure']['config']['interval'] = 1.0

# process 'autocatalysis'  (local:AutocatalysisODE)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['autocatalysis']['config']['k'] = 0.3
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['autocatalysis']['config']['k_cat'] = 0.15
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['autocatalysis']['config']['interval'] = 1.0

# process 'containment_closure'  (local:ContainmentClosureODE)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['containment_closure']['config']['assembly_rate'] = 0.15
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['containment_closure']['config']['perm_max'] = 0.8
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['containment_closure']['config']['perm_km'] = 1.0
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['containment_closure']['config']['interval'] = 1.0

# process 'membrane_self_assembly'  (local:MembraneSelfAssemblyODE)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['membrane_self_assembly']['config']['k'] = 0.2
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['membrane_self_assembly']['config']['interval'] = 1.0

# process 'lipid_aggregation'  (local:LipidAggregationODE)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['lipid_aggregation']['config']['k'] = 0.1
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['lipid_aggregation']['config']['interval'] = 1.0

# process 'replication_closure'  (local:ReplicationClosureODE)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['replication_closure']['config']['k'] = 0.2
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['replication_closure']['config']['interval'] = 1.0

# process 'template_replication'  (local:TemplateReplicationODE)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['template_replication']['config']['k'] = 0.15
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['template_replication']['config']['interval'] = 1.0

# process 'template_directed_synthesis'  (local:TemplateDirectedSynthesisProc)
spec_viva_meta_modelers_guide_composites_fig09a_executable['state']['template_directed_synthesis']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig09b-executable`** — `spec_viva_meta_modelers_guide_composites_fig09b_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig09b_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig09b-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig09b_executable)

# === Edit parameters for composite 'The Minimal Cell — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'minimal_cell_containment'  (local:ContainmentODE)
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_containment']['config']['assembly_rate'] = 0.15
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_containment']['config']['interval'] = 1.0

# process 'minimal_cell_metabolism'  (local:MetabolismLinear)
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_metabolism']['config']['k_cat'] = 0.2
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_metabolism']['config']['metabolite_yield'] = 0.6
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_metabolism']['config']['energy_yield'] = 0.4
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_metabolism']['config']['interval'] = 1.0

# process 'gene_expression'  (local:GeneExpressionODE)
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['gene_expression']['config']['k_expr'] = 0.25
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['gene_expression']['config']['protein_yield'] = 0.5
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['gene_expression']['config']['enzyme_yield'] = 0.3
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['gene_expression']['config']['interval'] = 1.0

# process 'minimal_cell_replication'  (local:ReplicationODE)
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_replication']['config']['k_rep'] = 0.1
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_replication']['config']['gene_yield'] = 0.5
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_replication']['config']['nucleic_yield'] = 0.4
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['minimal_cell_replication']['config']['interval'] = 1.0

# process 'diffusion'  (local:DiffusionRelax)
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['diffusion']['config']['turnover_rate'] = 0.05
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['diffusion']['config']['interval'] = 1.0

# process 'reactions'  (local:MassActionReactions)
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['reactions']['config']['k_react'] = 0.15
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['reactions']['config']['protein_yield'] = 0.4
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['reactions']['config']['nucleic_turnover'] = 0.2
spec_viva_meta_modelers_guide_composites_fig09b_executable['state']['reactions']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig10-1-executable`** — `spec_viva_meta_modelers_guide_composites_fig10_1_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_1_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-1-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_1_executable)

# === Edit parameters for composite 'Cell Division — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'dna_replication'  (local:DNAReplicationODE)
spec_viva_meta_modelers_guide_composites_fig10_1_executable['state']['dna_replication']['config']['k'] = 0.15
spec_viva_meta_modelers_guide_composites_fig10_1_executable['state']['dna_replication']['config']['interval'] = 1.0

# process 'segregate_chromosome'  (local:SegregateChromosomeProc)
spec_viva_meta_modelers_guide_composites_fig10_1_executable['state']['segregate_chromosome']['config']['seg_rate'] = 0.2
spec_viva_meta_modelers_guide_composites_fig10_1_executable['state']['segregate_chromosome']['config']['interval'] = 1.0

# process 'divide'  (local:DivisionRewrite)
spec_viva_meta_modelers_guide_composites_fig10_1_executable['state']['divide']['config']['division_time'] = 5.0
spec_viva_meta_modelers_guide_composites_fig10_1_executable['state']['divide']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig10-2-executable`** — `spec_viva_meta_modelers_guide_composites_fig10_2_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_2_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-2-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_2_executable)

# === Edit parameters for composite 'Biofilm Development — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'surface_attachment'  (local:SurfaceAttachmentProc)
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['surface_attachment']['config']['attach_rate'] = 0.15
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['surface_attachment']['config']['adhesion_coef'] = 0.5
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['surface_attachment']['config']['interval'] = 1.0

# process 'ecm_secretion'  (local:ECMSecretionProc)
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['ecm_secretion']['config']['k'] = 0.2
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['ecm_secretion']['config']['interval'] = 1.0

# process 'biofilm_growth'  (local:BiofilmGrowthProc)
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['biofilm_growth']['config']['mass_rate'] = 0.25
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['biofilm_growth']['config']['growth_rate'] = 0.08
spec_viva_meta_modelers_guide_composites_fig10_2_executable['state']['biofilm_growth']['config']['interval'] = 1.0

# **Composite `viva_meta_modelers_guide.composites.fig10-3-executable`** — `spec_viva_meta_modelers_guide_composites_fig10_3_executable` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_viva_meta_modelers_guide_composites_fig10_3_executable = load_spec(REPO / 'viva_meta_modelers_guide/composites/fig10-3-executable.composite.json')
describe_spec(spec_viva_meta_modelers_guide_composites_fig10_3_executable)

# === Edit parameters for composite 'Evolution — Executable' ===
# Each line is the spec's CURRENT value — change any, then run the Run cell
# below. The spec is a plain dict, so you may also add or remove keys.

# process 'variation'  (local:VariationProc)
spec_viva_meta_modelers_guide_composites_fig10_3_executable['state']['variation']['config']['interval'] = 1.0

# process 'selection'  (local:SelectionProc)
spec_viva_meta_modelers_guide_composites_fig10_3_executable['state']['selection']['config']['k'] = 0.3
spec_viva_meta_modelers_guide_composites_fig10_3_executable['state']['selection']['config']['interval'] = 1.0

# process 'port_addition'  (local:PortAdditionProc)
spec_viva_meta_modelers_guide_composites_fig10_3_executable['state']['port_addition']['config']['onset_rate'] = 0.1
spec_viva_meta_modelers_guide_composites_fig10_3_executable['state']['port_addition']['config']['capacity'] = 1.0
spec_viva_meta_modelers_guide_composites_fig10_3_executable['state']['port_addition']['config']['interval'] = 1.0

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: the-living-atlas ===
STUDY = 'the-living-atlas'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **the-living-atlas-dynamics**

# the-living-atlas-dynamics
_save_viz('the-living-atlas', 'the-living-atlas-dynamics', _render_one('image:visualizations/the-living-atlas-dynamics.svg', {'chart': 'image', 'caption': 'CLOSED-LOOP dynamics — conserved, run to completion.'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | peak-growth | kind=observable path=biomass expr=max(biomass) | op >= value 3.0 provenance biomass peaks then lyses (exec max≈8.4) |
# | disintegration | kind=observable path=debris expr=last(debris) | op >= value 2.0 provenance lysis converts biomass to debris (exec last≈7.3) |
# | division | kind=observable path=cell_count expr=last(cell_count) | op >= value 2.0 provenance the cell divides (exec cell_count 1→14) |
# | draft-is-inert | kind=observable path=biomass expr=max(biomass) | op >= value 3.0 provenance draft/knockout run collapses (no mechanism / no closure) |
